services:
  rap_cms:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: 'rap_cms'
    volumes:
      - .:/var/www/html/
    ports:
      - 8003:80

networks:
  default:
    external: true
    name: mysql
